### ISSUE TITLE
Custom Node Examples

### ISSUE THREAD

**Issue by Avindr** [Unity-Technologies/Unity.Animation.Samples#13]
Hi, 

Would it be possible to add an example for creating custom nodes to use in the graph. I'm an animation programmer and creator of 'Motion Matching for Unity'. 

It would be nice to have an example to show how to do this so we can implement complex animation behaviour nodes like internalisation, motion matching, stride warping etc. etc.

**Comment by oldio** [comment]
There's a few samples that showcase custom nodes such as the AnimationController and Inertialblending.
