### ISSUE TITLE
Version 0.4.0-preview.1 - May 08, 2020

### ISSUE THREAD

**Issue by nicolasgramlich** [Unity-Technologies/Unity.Animation.Samples#14]
Is it Christmas yet? 🎄

![image](https://user-images.githubusercontent.com/287060/81535333-776aa080-931e-11ea-8089-781512b9c447.png)

Sorry for the spammy post, but has anyone tried it yet? Any secret site where we can get samples?

The package site is arguably a "little" thin on information: https://docs.unity3d.com/Packages/com.unity.animation@0.4/manual/index.html

**Comment by nicolasgramlich** [comment]
Ok I spent like 3 hours trying to get it to work with various URP versions (`9.0.0-preview.14` and `8.1.0`) but the GPU instancing still doesn't seem to work with URP.

There is one interesting issue on (at least) URP `8.1.0`, which is that the model renders in a blue-ish tint, the moment I turn on `DOTS Instancing` on the `PBR Master` and save the shadergraph:

Left side is: ✅ `Dots Instancing`
Right side is ⛔ `Dots Instancing` 
![image](https://user-images.githubusercontent.com/287060/81544441-66c12700-932c-11ea-9371-a22783f8a5f5.png)

**Comment by cdm456852** [comment]
> Ok I spent like 3 hours trying to get it to work with various URP versions (`9.0.0-preview.14` and `8.1.0`) but the GPU instancing still doesn't seem to work with URP.
> 
> There is one interesting issue on (at least) URP `8.1.0`, which is that the model renders in a blue-ish tint, the moment I turn on `DOTS Instancing` on the `PBR Master` and save the shadergraph:
> 
> Left side is: ✅ `Dots Instancing`
> Right side is ⛔ `Dots Instancing`
> ![image](https://user-images.githubusercontent.com/287060/81544441-66c12700-932c-11ea-9371-a22783f8a5f5.png)

Hi, Can you tell me how to achieve this with URP? Because I have been waiting for too long, And the unity team still not answer our question of the support of the URP.

**Comment by nicolasgramlich** [comment]
Unless you somehow figure out the Instancing issue (or have literally only one model to be animated) it's not going to be worth your efforts.

That being sad, I effectively just tried to enable anything related `GPU Instancing` `DOTS Instancing ` and `Hybrid Instanced (experimental)` on materials/shadergraphs and enable the SRP Batcher when trying it with the Hybrid Renderer v2.

More info here: https://docs.unity3d.com/Packages/com.unity.rendering.hybrid@0.5/manual/index.html

Coincidentally a couple new package shave landed today (May 25th), so you might be more lucky now!

**Comment by cdm456852** [comment]
> Unless you somehow figure out the Instancing issue (or have literally only one model to be animated) it's not going to be worth your efforts.
> 
> That being sad, I effectively just tried to enable anything related `GPU Instancing` `DOTS Instancing ` and `Hybrid Instanced (experimental)` on materials/shadergraphs and enable the SRP Batcher when trying it with the Hybrid Renderer v2.
> 
> More info here: https://docs.unity3d.com/Packages/com.unity.rendering.hybrid@0.5/manual/index.html
> 
> Coincidentally a couple new package shave landed today (May 25th), so you might be more lucky now!

Thanks for your answer, But what I mean is that is it possible to let this dots animation working on the URP environment without saying performance or something. If it can do that, Please tell me how to do that, Thank you!!

**Comment by nicolasgramlich** [comment]
If I understood you right, I don't think you'll have success quite yet. I'll keep trying periodically, since animations are the last thing to make my game complete and update on my success here.

**Comment by nicolasgramlich** [comment]
There have been two small updated since I tried, but they seem very minor, so nothing has changed yet most likelt: https://docs.unity3d.com/Packages/com.unity.animation@0.4/changelog/CHANGELOG.html

**Comment by MyelinsheathXD** [comment]
I really love the concept! since now it would be easy to create Creature animation by hand made or mocap anim data!
Is this method is just lerp anim transition?, I am too curious about it  !!!

**Comment by nicolasgramlich** [comment]
Closing in favor of #15
