### ISSUE TITLE
Is there still no new news about the URP DOTS Animation? How about the latest version of Animation Package?Does there has a sample based on the latest version of Animation package?

### ISSUE THREAD

**Issue by cdm456852** [Unity-Technologies/Unity.Animation.Samples#16]
Is there still no new news about the URP DOTS Animation? How about the latest version of Animation Package?Does there has a sample based on the latest version of Animation package?

**Comment by audegi** [comment]
Hello! We've just updated master with the latest animation package samples, and added some URP samples.
