### ISSUE TITLE
Use animations from mixamo

### ISSUE THREAD

**Issue by firesgc** [Unity-Technologies/Unity.Animation.Samples#23]
Hello!

I am trying to play my own animation with the new animation system (com.unity.animation 0.8.0-preview.4).
For testing I use the Animation Sample Project (https://github.com/Unity-Technologies/Unity.Animation.Samples), which works without problems and I have my own animation from https://www.mixamo.com/#/.
If I replace the original animation with one from mixamo the character will not be animated anymore.

Unfortunately, I get neither warnings nor errors which leaves me completely in the dark about what the problem might be.
Thanks for the help!

ps: If I use the Rig_TerraformerLOD0 character with the "mixamo animation" with the old animation system (with animator and controller) both works perfectly together.

**Comment by chungggg** [comment]
Mixamo animation doesn't work for you because Animation Clip is not map to 3D model, if you want mixamo animtion work with other 3D model you need use Retarget sample

**Comment by firesgc** [comment]
All right! Thank you very much!
