### ISSUE TITLE
Retargeting skeletons with different optional bones

### ISSUE THREAD

**Issue by gamemachine** [Unity-Technologies/Unity.Animation.Samples#7]
This seems to short circuit the whole flow somehow.  Any insight into why?

**Comment by gamemachine** [comment]
Issue wasn't retargeting, it's just incomplete handling of some clip setups.

**Comment by johnsoncodehk** [comment]
Can you share the relevant clip setups? It will be very helpful

**Comment by gamemachine** [comment]
I would if I could remember, a lot of iteration/learning since that happened.

**Comment by johnsoncodehk** [comment]
Thanks in advance!
